name: Run Python Tests

# This workflow runs on every push to the main branch
# and on every pull request that targets the main branch.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest version of Ubuntu
    strategy:
      matrix:
        # Test against a specific version of Python
        python-version: ["3.11"]

    steps:
      # 1. Check out your repository's code
      - uses: actions/checkout@v4

      # 2. Set up the specified Python version
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # 3. Install project dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      # 4. Run the tests using pytest
      - name: Test with pytest
        run: |
          pytest
